-- Curated short labels for the 97 HS2 (SH2) chapters, in Portuguese and English.
-- The HS2 chapter list is a stable international standard (not Brazil-specific
-- or data-dependent), so this is a one-time static lookup rather than
-- something the Cloud Function needs to regenerate on every run. Chapter 77
-- is reserved by the HS standard and has no official name.
CREATE OR REPLACE TABLE `your_project.trade_data.sh2_labels` (
  co_sh2      INT64   NOT NULL,
  no_sh2_curto_por STRING,
  no_sh2_curto_ing STRING
);

INSERT INTO `your_project.trade_data.sh2_labels` (co_sh2, no_sh2_curto_por, no_sh2_curto_ing) VALUES
(1,  'Animais vivos',                       'Live animals'),
(2,  'Carnes',                              'Meat'),
(3,  'Peixes e frutos do mar',              'Fish and seafood'),
(4,  'Laticínios, ovos, mel',               'Dairy, eggs, honey'),
(5,  'Outros produtos de origem animal',    'Other animal products'),
(6,  'Plantas vivas',                       'Live plants'),
(7,  'Legumes e hortaliças',                'Vegetables'),
(8,  'Frutas e frutos secos',               'Fruits and nuts'),
(9,  'Café, chá, especiarias',              'Coffee, tea, spices'),
(10, 'Cereais',                             'Cereals'),
(11, 'Produtos de moagem, malte, amidos',   'Milling products, malt, starches'),
(12, 'Sementes e grãos oleaginosos',        'Oil seeds and grains'),
(13, 'Gomas e resinas',                     'Gums and resins'),
(14, 'Matérias para entrançar',             'Vegetable plaiting materials'),
(15, 'Gorduras e óleos animais/vegetais',   'Animal/vegetable fats and oils'),
(16, 'Preparações de carne e peixe',        'Meat/fish preparations'),
(17, 'Açúcares',                            'Sugars'),
(18, 'Cacau',                               'Cocoa'),
(19, 'Preparações de cereais e farinha',    'Cereal/flour preparations'),
(20, 'Preparações de vegetais e frutas',    'Vegetable/fruit preparations'),
(21, 'Preparações alimentícias diversas',   'Miscellaneous food preparations'),
(22, 'Bebidas',                             'Beverages'),
(23, 'Resíduos alimentares, ração animal',  'Food residues, animal feed'),
(24, 'Tabaco',                              'Tobacco'),
(25, 'Sal, pedra, cimento',                 'Salt, stone, cement'),
(26, 'Minérios, escórias, cinzas',          'Ores, slag, ash'),
(27, 'Combustíveis minerais, óleos',        'Mineral fuels, oils'),
(28, 'Químicos inorgânicos',                'Inorganic chemicals'),
(29, 'Químicos orgânicos',                  'Organic chemicals'),
(30, 'Produtos farmacêuticos',              'Pharmaceuticals'),
(31, 'Fertilizantes',                       'Fertilizers'),
(32, 'Extratos para tingir, tintas',        'Tanning/dyeing extracts, paints'),
(33, 'Perfumaria e cosméticos',             'Perfumery and cosmetics'),
(34, 'Sabões e ceras',                      'Soaps and waxes'),
(35, 'Colas e enzimas',                     'Glues and enzymes'),
(36, 'Explosivos e pirotecnia',             'Explosives and pyrotechnics'),
(37, 'Produtos fotográficos',               'Photographic goods'),
(38, 'Produtos químicos diversos',          'Miscellaneous chemical products'),
(39, 'Plásticos',                           'Plastics'),
(40, 'Borracha',                            'Rubber'),
(41, 'Peles e couros crus',                 'Raw hides and skins'),
(42, 'Artigos de couro',                    'Leather goods'),
(43, 'Peles com pelo',                      'Furskins'),
(44, 'Madeira',                             'Wood'),
(45, 'Cortiça',                             'Cork'),
(46, 'Obras de espartaria',                 'Straw/basketware'),
(47, 'Pasta de madeira',                    'Wood pulp'),
(48, 'Papel e papelão',                     'Paper and paperboard'),
(49, 'Livros impressos',                    'Printed books'),
(50, 'Seda',                                'Silk'),
(51, 'Lã',                                  'Wool'),
(52, 'Algodão',                             'Cotton'),
(53, 'Outras fibras têxteis vegetais',      'Vegetable textile fibers'),
(54, 'Filamentos sintéticos',               'Man-made filaments'),
(55, 'Fibras sintéticas descontínuas',      'Man-made staple fibers'),
(56, 'Falsos tecidos, feltros',             'Wadding, felt, nonwovens'),
(57, 'Tapetes',                             'Carpets'),
(58, 'Tecidos especiais',                   'Special woven fabrics'),
(59, 'Tecidos impregnados',                 'Impregnated textile fabrics'),
(60, 'Tecidos de malha',                    'Knitted fabrics'),
(61, 'Vestuário de malha',                  'Apparel, knitted'),
(62, 'Vestuário, exceto malha',             'Apparel, not knitted'),
(63, 'Outros artigos têxteis',              'Textile articles'),
(64, 'Calçados',                            'Footwear'),
(65, 'Chapéus',                             'Headgear'),
(66, 'Guarda-chuvas, bengalas',             'Umbrellas, canes'),
(67, 'Penas, flores artificiais',           'Feathers, artificial flowers'),
(68, 'Obras de pedra, gesso, cimento',      'Stone/plaster/cement articles'),
(69, 'Cerâmica',                            'Ceramics'),
(70, 'Vidro',                               'Glass'),
(71, 'Pedras preciosas, joias',             'Precious stones, jewelry'),
(72, 'Ferro e aço',                         'Iron and steel'),
(73, 'Obras de ferro e aço',                'Iron/steel articles'),
(74, 'Cobre',                               'Copper'),
(75, 'Níquel',                              'Nickel'),
(76, 'Alumínio',                            'Aluminum'),
(78, 'Chumbo',                              'Lead'),
(79, 'Zinco',                               'Zinc'),
(80, 'Estanho',                             'Tin'),
(81, 'Outros metais comuns',                'Other base metals'),
(82, 'Ferramentas, cutelaria',              'Tools, cutlery'),
(83, 'Obras diversas de metal',             'Miscellaneous metal articles'),
(84, 'Máquinas',                            'Machinery'),
(85, 'Máquinas elétricas, eletrônicos',     'Electrical machinery, electronics'),
(86, 'Material ferroviário',                'Railway vehicles'),
(87, 'Veículos',                            'Vehicles'),
(88, 'Aeronaves',                           'Aircraft'),
(89, 'Embarcações',                         'Ships and boats'),
(90, 'Instrumentos ópticos e médicos',      'Optical/medical instruments'),
(91, 'Relógios',                            'Clocks and watches'),
(92, 'Instrumentos musicais',               'Musical instruments'),
(93, 'Armas e munições',                    'Arms and ammunition'),
(94, 'Móveis, iluminação',                  'Furniture, lighting'),
(95, 'Brinquedos, jogos, esportes',         'Toys, games, sports equipment'),
(96, 'Manufaturas diversas',                'Miscellaneous manufactured articles'),
(97, 'Obras de arte, antiguidades',         'Art, antiques');
